#!/bin/bash
#Recursive dependences building from AUR.
# input: package
# output: packages list
# After this, recursive calling ckit -Bain $list ?
# Is this a good solution for this job? ....working on it
# BAAAAARDO HELP ME :°D

builddir="$HOME/pkg/workspace"

#dependences(){

    deps=()

    source "$builddir/$1/PKGBUILD"

    # depends
    for pkg in "${depends[@]}"; do
        pacman -Si "$pkg" &>/dev/null
        (( "$?" == 1 )) && deps+=($pkg)
    done

    # makedepends
    for pkg in "${makedepends[@]}"; do
        pacman -Si "$pkg" &>/dev/null
        (( "$?" == 1 )) && deps+=($pkg)
    done

    if (( "${#deps[@]}" > 0 )); then
        echo "Missing depends:"
        for dep in "${deps[@]}"; do
            echo "$dep"
        done
    fi

#}

